(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const local=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch(_){return f}};
function text(sel,v){const e=$(sel);if(e&&String(v??'').trim())e.textContent=v}
function renderProjects(items){const grid=$('#projectGrid');if(!grid)return;const live=(items||[]).filter(x=>x&&x.published!==false).sort((a,b)=>(a.order||999)-(b.order||999)).slice(0,3);if(!live.length)return;grid.innerHTML=live.map((p,i)=>'<article class="work-card '+(i===0?'tall':'')+'"><div class="work-art art-'+(i+1)+'">'+(p.image?'<img loading="lazy" src="'+esc(p.image)+'" alt="'+esc(p.alt||p.title||'Workshop project')+'" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.55">':'')+'<span class="art-code">AKH / '+String(i+1).padStart(3,'0')+'</span><span class="art-title">'+esc(p.title||p.name||'Workshop Project')+'</span></div><div class="work-info"><span>'+String(i+1).padStart(2,'0')+'</span><div><h3>'+esc(p.title||p.name||'Workshop Project')+'</h3><p>'+esc(p.description||'Engineering and workshop project.')+'</p></div></div></article>').join('')}
async function firebaseSync(){if(!window.AKHI_FIREBASE?.ready)return false;try{const db=window.AKHI_FIREBASE.db;const [home,banners,projects,settings]=await Promise.all([db.collection('siteContent').doc('home').get(),db.collection('banners').where('published','==',true).limit(12).get(),db.collection('projects').where('published','==',true).limit(12).get(),db.collection('siteContent').doc('settings').get()]);if(home.exists){const h=home.data();text('[data-cms="heroTitle"]',h.heroTitle);text('[data-cms="heroDescription"]',h.heroDescription)}if(settings.exists){const s=settings.data();document.querySelectorAll('[data-cms="businessName"]').forEach(e=>e.textContent=s.name||e.textContent)}renderProjects(projects.docs.map(d=>({id:d.id,...d.data()})));return true}catch(err){console.warn('[AKHI] public Firebase sync failed:',err);return false}}
function fallback(){const p=local('aki_projects_v1',[]);renderProjects(p)}
function reveal(){if(!('IntersectionObserver'in window)){document.querySelectorAll('.reveal').forEach(e=>e.classList.add('is-visible'));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>o.observe(e))}
function clock(){const e=$('#clock');if(e)e.textContent=new Intl.DateTimeFormat('en-BD',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())+' • WORKSHOP'}
async function init(){text('#year',new Date().getFullYear());clock();setInterval(clock,30000);const ok=await firebaseSync();if(!ok)fallback();reveal()}
window.addEventListener('load',init);
})();
