backend:
  name: github
  repo: shahneilkhan/akhiengineeringworkshop.github.io
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: shop
    label: Shop
    files:
      - name: products
        label: Chair Products
        file: data/products.json
        fields:
          - label: Products
            name: products
            widget: list
            summary: "{{fields.name}} - {{fields.price}}৳"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Price (৳), name: price, widget: number, value_type: int, min: 0 }
              - { label: Image, name: image, widget: image }
              - { label: Hot badge, name: hot, widget: boolean, default: false }
